"""
Django settings for attandSystem project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gp6_&!)p8ns6x7q27qk$v$nf*$c6no(0*qkqjohux#i4&&n(ah'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'systemApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'systemApp.middleware.internet_middleware.InternetCheckMiddleware',
]

ROOT_URLCONF = 'attandSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["static"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attandSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'systemApp.CustomUser'

LOGIN_URL = '/accounts/login/'

JAZZMIN_SETTINGS = { 
    # title of the window (Will default to current_admin_site.site_title if absent or None) 
    "site_title": "Recon-AI", 
 
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None) 
    "site_header": "Recon-AI", 
 
    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None) 
    "site_brand": "Recon-AI", 
 
    # Logo to use for your site, must be present in static files, used for brand on top left 
    "site_logo": "dgt.jpg", 
 
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo) 
    "login_logo": "dgt.jpg", 
    
    # Other settings...
    "custom_css": "css/custom_login.css",  # Path to your custom CSS
     
    # Logo to use for login form in dark themes (defaults to login_logo) 
    "login_logo_dark": None, 
 
    # CSS classes that are applied to the logo above 
    "site_logo_classes": "img-circle", 
 
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px) 
    "site_icon": None, 
 
    # Welcome text on the login screen 
    "welcome_sign": "Welcome to the Recon-AI Admin Panel", 
    # Copyright on the footer 
    "copyright": "Recon-AI", 
    # Add a language dropdown into the admin 
    # "language_chooser": True, 
    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user 
    "user_avatar": None, 
}


