# Generated by Django 5.0.3 on 2024-03-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='registration_id',
            new_name='registration',
        ),
    ]
