# Generated by Django 5.0.3 on 2024-03-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemApp', '0002_rename_registration_id_attendance_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='registration',
        ),
    ]
