# Generated by Django 5.1.1 on 2024-09-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemApp', '0003_remove_attendance_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
