# Generated by Django 5.1.1 on 2024-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemApp', '0005_remove_attendance_points_attendance_voice_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='eye_points',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_points',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
